### ISSUE TITLE
Comparison operators

### ISSUE THREAD

**Issue by pscadiz** [spotify/puppetexplorer#39]
Using puppet 1.5.0 since puppetdb version is 2.3.5

=,  != and ~ are the only comparison operators that work

using <= returns the error that it's expecting = to be the string
Expecting '@', 'Boolean', 'Number', 'String', got '='

using < returns an Error 500 from the puppetdb
<h2>HTTP ERROR: 500</h2> <p>Problem accessing /v4/nodes. Reason: <pre> Assert failed: (jdbc/valid-jdbc-query? (:results-query %))</pre></p> <hr /><i><small>Powered by Jetty://</small></i>

using !~ is a lexical error

Have these issues been resolved in updates? Kindly explain how the error is caused as well.

Thanks!

**Comment by dalen** [comment]
This was a bug in node-puppetdbquery. I just fixed it in https://github.com/dalen/node-puppetdbquery/commit/bce0fa39815ba89fe240a95d48b8d2336c95afcb

The order of >= and > was wrong in the lexer, so it matched them as `>` and `=` instead of as `>=`.
!~ was just missing from the lexer (but present in grammar and evaluator) so I added that.

And also added tests for all these things while at it :)

To get them fixed in puppetexplorer I will need to build a new version. Will try to do that soon, might need to backport this fix for 1.5.x.

What is the full query using the `>` operator that gives you a 500 error from puppetdb?

**Comment by pscadiz** [comment]
Thanks for the quick reply!

Query that returned the error 500 was
puppetversion < "3.8.3"

**Comment by smortex** [comment]
As a result of a build from the latest source today, the query `puppetversion < "3.8.4"` still produces an error with PuppetDB 3.2.3:
> Failed to fetch /api/pdb/query/v4/fact-contents
> 400: Bad Request`

The GET request itself (the one that has a 400 return status) reports:

> Argument "3.8.4" and operator "<" have incompatible types.

As @pscadiz originally reported, only the `=`, `!=` and `~` operators produce correct results.

Worse: examples for the landing page such as _processorcount=4_ do not work without quoting the value (`processorcount="4"`). In such a condition the result is an empty JSON response, without error.

I'm new to puppetexplorer and can't say if the problems are related or if another issue should be opened for this problem.

**Comment by dalen** [comment]
`puppetversion<"3.8.4"` won't work with puppetdb as that fact is a string and they only support the `=`, `!=` or `~` operators.

Regarding the processorcount comparison you have to set `stringify_facts=false` in order for that to work on puppet 3.x. Otherwise it turns all facts into strings. See: https://docs.puppetlabs.com/puppet/3.8/reference/config_important_settings.html#getting-new-features-early

**Comment by smortex** [comment]
Thanks for the hint @dalen ! This is a part of my problem, the other seems to be facter-2.2.0 as suggested in #20 when searching with the right keywords :wink: …
